### ISSUE TITLE
Pam's Issue

### ISSUE THREAD

**Issue by gwf313** [Y0ungSandwich/Mech-Magic-Rewind#7]
Mass crafting of items at a time caused a crash to the game. Crafting one at a time works fine.

[crash-2019-07-17_13.03.37-client.txt](https://github.com/Y0ungSandwich/Mech-Magic-Rewind/files/3403275/crash-2019-07-17_13.03.37-client.txt)

**Comment by Y0ungSandwich** [comment]
I can't replicate. Do you remember the specific recipes you were trying?

**Comment by gwf313** [comment]
I was trying to make blueberry juice and it crashed when I tried to make a
stack at a time.

**Comment by Y0ungSandwich** [comment]
Interesting. No issues here crafting a stack of blueberry juice. Let me know if you run into any other crafting issues with pam's.
